# Market64 v0.1.2-beta by @tbm00
# https://github.com/tbm00/Market64

enabled: true

mysql:
  host: 'host'
  port: 3306
  database: 'db'
  username: 'user'
  password: 'pass'
  useSSL: false
  hikari:
    maximumPoolSize: 16
    minimumPoolSize: 2
    idleTimeout: 240 # 4 minutes
    connectionTimeout: 30 # 30 seconds
    maxLifetime: 1800 # 30 minutes
    leakDetection:
      enabled: false
      threshold: 2 # 2 seconds

lang:
  prefix: "&8[&fMarket&8] &7"

feature:
  enabled: true
