name: Market64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.market64.Market64
api-version: 1.17
depend: [DisplayShops, WorldGuard, GriefDefender, Vault]
commands:
  stall:
    description: Main command for Market64
  stalladmin:
    description: Admin commands for Market64
permissions:
  market64.player:
    description: Ability to use player commands
    default: true
  market64.admin:
    description: Ability to use admin commands
    default: op