name: ShopStalls64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.shopstalls64.ShopStalls64
api-version: 1.17
depend: [DisplayShops, GriefDefender, Vault, Rep64]
commands:
  teststall:
    description: Main command for ShopStalls64
  teststalladmin:
    description: Admin commands for ShopStalls64
permissions:
  shopstalls64.player:
    description: Ability to use player commands
    default: true
  shopstalls64.admin:
    description: Ability to use admin commands
    default: op